/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheSpaceRouteImport } from './routes/the-space'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as Level5EventsRouteImport } from './routes/level-5-events'
import { Route as Level4DiningRouteImport } from './routes/level-4-dining'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TheSpaceRoute = TheSpaceRouteImport.update({
  id: '/the-space',
  path: '/the-space',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const Level5EventsRoute = Level5EventsRouteImport.update({
  id: '/level-5-events',
  path: '/level-5-events',
  getParentRoute: () => rootRouteImport,
} as any)
const Level4DiningRoute = Level4DiningRouteImport.update({
  id: '/level-4-dining',
  path: '/level-4-dining',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/level-4-dining': typeof Level4DiningRoute
  '/level-5-events': typeof Level5EventsRoute
  '/menu': typeof MenuRoute
  '/the-space': typeof TheSpaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/level-4-dining': typeof Level4DiningRoute
  '/level-5-events': typeof Level5EventsRoute
  '/menu': typeof MenuRoute
  '/the-space': typeof TheSpaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/level-4-dining': typeof Level4DiningRoute
  '/level-5-events': typeof Level5EventsRoute
  '/menu': typeof MenuRoute
  '/the-space': typeof TheSpaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/level-4-dining'
    | '/level-5-events'
    | '/menu'
    | '/the-space'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/level-4-dining'
    | '/level-5-events'
    | '/menu'
    | '/the-space'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/level-4-dining'
    | '/level-5-events'
    | '/menu'
    | '/the-space'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  Level4DiningRoute: typeof Level4DiningRoute
  Level5EventsRoute: typeof Level5EventsRoute
  MenuRoute: typeof MenuRoute
  TheSpaceRoute: typeof TheSpaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-space': {
      id: '/the-space'
      path: '/the-space'
      fullPath: '/the-space'
      preLoaderRoute: typeof TheSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-5-events': {
      id: '/level-5-events'
      path: '/level-5-events'
      fullPath: '/level-5-events'
      preLoaderRoute: typeof Level5EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-4-dining': {
      id: '/level-4-dining'
      path: '/level-4-dining'
      fullPath: '/level-4-dining'
      preLoaderRoute: typeof Level4DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  Level4DiningRoute: Level4DiningRoute,
  Level5EventsRoute: Level5EventsRoute,
  MenuRoute: MenuRoute,
  TheSpaceRoute: TheSpaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
